name: Fetch Data

on:
  schedule:
    - cron: '0 0,12 * * *'  # 每天的0點和12點運行
  workflow_dispatch:  # 手動觸發

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch_data_script.py
        run: python fetch_data_script.py

      - name: Upload data.json
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: data.json

      - name: Copy data.json to repository
        run: cp data.json $GITHUB_WORKSPACE/data.json

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data.json
          git commit -m "Update data.json"
          git push
